FROM fedora:25
SHELL ["/bin/bash", "-c"]

# dependencies
RUN dnf -y groups install 'Development tools'
RUN dnf -y install
    autoconf libtool pkgconfig \
    python-devel python-pip python2-virtualenv \

# needed for build time
# https://stackoverflow.com/questions/34624428/g-error-usr-lib-rpm-redhat-redhat-hardened-cc1-no-such-file-or-directory
RUN dnf -y install redhat-rpm-config

# needed for install script, might not be installed
RUN dnf -y install curl

RUN useradd --home-dir /home/chaum --create-home --shell /bin/bash --skel /etc/skel/ chaum
USER chaum

# copy node software from the host and install
COPY bitcoin-0.14.2-x86_64-linux-gnu.tar.gz /home/chaum
WORKDIR /home/chaum
RUN tar xaf bitcoin-0.14.2-x86_64-linux-gnu.tar.gz
ENV PATH "/home/chaum/bitcoin-0.14.2/bin:${PATH}"
RUN bitcoind --help 1>/dev/null || false

# install script 
RUN curl -L -O https://github.com/fivepiece/joinmarket-clientserver/archive/test_travis.tar.gz
RUN tar xaf test_travis.tar.gz
WORKDIR "joinmarket-clientserver-test_travis"
RUN ./install.sh
RUN source jmvenv/bin/activate && ./test/run_tests.sh
